module.exports = {
    "action": "requested",
    "check_suite": {
        "id": 27423697,
        "node_id": "MDEwOkNoZWNrU3VpdGUyNzQyMzY5Nw==",
        "head_branch": "test-branch",
        "head_sha": "c636c1850d1999ec78f1bfa6e31055bc2e000691",
        "status": "queued",
        "conclusion": null,
        "url": "https://api.github.com/repos/austinkregel/test/check-suites/27423697",
        "before": "090d3dd4932abbb30a4ec5a673aab35edf7a49ed",
        "after": "c636c1850d1999ec78f1bfa6e31055bc2e000691",
        "pull_requests": [
            {
                "url": "https://api.github.com/repos/austinkregel/test/pulls/1",
                "id": 230020219,
                "number": 1,
                "head": {
                    "ref": "test-branch",
                    "sha": "c636c1850d1999ec78f1bfa6e31055bc2e000691",
                    "repo": {
                        "id": 157159428,
                        "url": "https://api.github.com/repos/austinkregel/test",
                        "name": "test"
                    }
                },
                "base": {
                    "ref": "master",
                    "sha": "767ae6f84a660501391a4e1f038ddc1fb7decbd7",
                    "repo": {
                        "id": 157159428,
                        "url": "https://api.github.com/repos/austinkregel/test",
                        "name": "test"
                    }
                }
            }
        ],
        "app": {
            "id": 20603,
            "node_id": "MDM6QXBwMjA2MDM=",
            "owner": {
                "login": "austinkregel",
                "id": 5355937,
                "node_id": "MDQ6VXNlcjUzNTU5Mzc=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5355937?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/austinkregel",
                "html_url": "https://github.com/austinkregel",
                "followers_url": "https://api.github.com/users/austinkregel/followers",
                "following_url": "https://api.github.com/users/austinkregel/following{/other_user}",
                "gists_url": "https://api.github.com/users/austinkregel/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/austinkregel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/austinkregel/subscriptions",
                "organizations_url": "https://api.github.com/users/austinkregel/orgs",
                "repos_url": "https://api.github.com/users/austinkregel/repos",
                "events_url": "https://api.github.com/users/austinkregel/events{/privacy}",
                "received_events_url": "https://api.github.com/users/austinkregel/received_events",
                "type": "User",
                "site_admin": false
            },
            "name": "DIY CI",
            "description": "A new an personal CI option",
            "external_url": "https://austinkregel.com",
            "html_url": "https://github.com/apps/diy-ci",
            "created_at": "2018-11-12T03:24:01Z",
            "updated_at": "2018-11-12T05:18:02Z"
        },
        "created_at": "2018-11-12T06:04:32Z",
        "updated_at": "2018-11-12T06:04:32Z",
        "latest_check_runs_count": 0,
        "check_runs_url": "https://api.github.com/repos/austinkregel/test/check-suites/27423697/check-runs",
        "head_commit": {
            "id": "c636c1850d1999ec78f1bfa6e31055bc2e000691",
            "tree_id": "215ddabceace542fdfbede0b1fb50a3097634e04",
            "message": "Update with echo",
            "timestamp": "2018-11-12T06:04:27Z",
            "author": {
                "name": "Austin Kregel",
                "email": "austin@kbcomp.co"
            },
            "committer": {
                "name": "Austin Kregel",
                "email": "austin@kbcomp.co"
            }
        }
    },
    "repository": {
        "id": 157159428,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNTcxNTk0Mjg=",
        "name": "test",
        "full_name": "austinkregel/test",
        "private": true,
        "owner": {
            "login": "austinkregel",
            "id": 5355937,
            "node_id": "MDQ6VXNlcjUzNTU5Mzc=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/5355937?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/austinkregel",
            "html_url": "https://github.com/austinkregel",
            "followers_url": "https://api.github.com/users/austinkregel/followers",
            "following_url": "https://api.github.com/users/austinkregel/following{/other_user}",
            "gists_url": "https://api.github.com/users/austinkregel/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/austinkregel/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/austinkregel/subscriptions",
            "organizations_url": "https://api.github.com/users/austinkregel/orgs",
            "repos_url": "https://api.github.com/users/austinkregel/repos",
            "events_url": "https://api.github.com/users/austinkregel/events{/privacy}",
            "received_events_url": "https://api.github.com/users/austinkregel/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/austinkregel/test",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/austinkregel/test",
        "forks_url": "https://api.github.com/repos/austinkregel/test/forks",
        "keys_url": "https://api.github.com/repos/austinkregel/test/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/austinkregel/test/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/austinkregel/test/teams",
        "hooks_url": "https://api.github.com/repos/austinkregel/test/hooks",
        "issue_events_url": "https://api.github.com/repos/austinkregel/test/issues/events{/number}",
        "events_url": "https://api.github.com/repos/austinkregel/test/events",
        "assignees_url": "https://api.github.com/repos/austinkregel/test/assignees{/user}",
        "branches_url": "https://api.github.com/repos/austinkregel/test/branches{/branch}",
        "tags_url": "https://api.github.com/repos/austinkregel/test/tags",
        "blobs_url": "https://api.github.com/repos/austinkregel/test/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/austinkregel/test/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/austinkregel/test/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/austinkregel/test/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/austinkregel/test/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/austinkregel/test/languages",
        "stargazers_url": "https://api.github.com/repos/austinkregel/test/stargazers",
        "contributors_url": "https://api.github.com/repos/austinkregel/test/contributors",
        "subscribers_url": "https://api.github.com/repos/austinkregel/test/subscribers",
        "subscription_url": "https://api.github.com/repos/austinkregel/test/subscription",
        "commits_url": "https://api.github.com/repos/austinkregel/test/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/austinkregel/test/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/austinkregel/test/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/austinkregel/test/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/austinkregel/test/contents/{+path}",
        "compare_url": "https://api.github.com/repos/austinkregel/test/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/austinkregel/test/merges",
        "archive_url": "https://api.github.com/repos/austinkregel/test/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/austinkregel/test/downloads",
        "issues_url": "https://api.github.com/repos/austinkregel/test/issues{/number}",
        "pulls_url": "https://api.github.com/repos/austinkregel/test/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/austinkregel/test/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/austinkregel/test/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/austinkregel/test/labels{/name}",
        "releases_url": "https://api.github.com/repos/austinkregel/test/releases{/id}",
        "deployments_url": "https://api.github.com/repos/austinkregel/test/deployments",
        "created_at": "2018-11-12T05:08:59Z",
        "updated_at": "2018-11-12T05:14:02Z",
        "pushed_at": "2018-11-12T06:04:31Z",
        "git_url": "git://github.com/austinkregel/test.git",
        "ssh_url": "git@github.com:austinkregel/test.git",
        "clone_url": "https://github.com/austinkregel/test.git",
        "svn_url": "https://github.com/austinkregel/test",
        "homepage": null,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
    },
    "sender": {
        "login": "austinkregel",
        "id": 5355937,
        "node_id": "MDQ6VXNlcjUzNTU5Mzc=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5355937?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/austinkregel",
        "html_url": "https://github.com/austinkregel",
        "followers_url": "https://api.github.com/users/austinkregel/followers",
        "following_url": "https://api.github.com/users/austinkregel/following{/other_user}",
        "gists_url": "https://api.github.com/users/austinkregel/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/austinkregel/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/austinkregel/subscriptions",
        "organizations_url": "https://api.github.com/users/austinkregel/orgs",
        "repos_url": "https://api.github.com/users/austinkregel/repos",
        "events_url": "https://api.github.com/users/austinkregel/events{/privacy}",
        "received_events_url": "https://api.github.com/users/austinkregel/received_events",
        "type": "User",
        "site_admin": false
    },
    "installation": {
        "id": 448448,
        "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uNDQ4NDQ4"
    }
}
